FoodApp/FoodApp/urls.py
from django.contrib import admin
from django.urls import path
from FoodServices import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.showAddressUI,name="loadAddress"),
    path('addAddress/',views.addAddressUI,name="addAddress"),
    path('editAddress/',views.editAddress,name="editAddress"),
    path('signUp/',views.displaySignUpForm,name="signUp"),
    path('verifyUser/',views.verifyUserUI,name="verifyUser"),
    path('signin/',views.displayform,name="signin"),
    path('feedbackForm/',views.displayFeedbackForm,name="feedbackForm"),
    path('dashboardFoodProvider/',views.displayFPOrderList,name="dashboardFoodProvider"),
    path('dashboardFoodSeeker/',views.displayFSOrderList,name="dashboardFoodSeeker")
]

FoodApp/FoodServices/models.py
from django.db import models
from django.forms.fields import IntegerField

class Order(models.Model):
	order_id=models.AutoField(primary_key=True)
	veg_healthy=models.IntegerField(null=True)
	veg_ill=models.IntegerField(null=True)
	nonveg_healthy=models.IntegerField(null=True)
	nonveg_ill=models.IntegerField(null=True)
	allergies=models.CharField(max_length=200,null=True)
	delivery_address=models.CharField(max_length=200)
	status=models.CharField(max_length=50)  #active, dispatched or delivered
	food_seeker_id=models.IntegerField()
	food_provider_id=models.IntegerField(null=True)


class FoodSeeker(models.Model):
	fs_id=models.AutoField(primary_key=True)
	name=models.CharField(max_length=100)
	mobile=models.CharField(null=True,max_length=10)
	email=models.CharField(max_length=100)

class FoodProvider(models.Model):
    fp_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100)
    mobile=models.CharField(null=True,max_length=10)
    email=models.CharField(max_length=100)
    ratings = models.IntegerField(null=True,default=0)

    def setDetails(self,User):

        fp_new=FoodProvider()
        fp_new.name=User['name']
        fp_new.mobile=User['mobile-number']
        fp_new.email=User['email']

        fp_new.save()

        return fp_new


class Address(models.Model):  
    add_id =  models.BigAutoField(primary_key=True)
    building = models.CharField(max_length=100)
    street = models.CharField(max_length=100, default = '')
    landmark = models.CharField(max_length=100, default = '')
    city = models.CharField(max_length=100, default = '')
    state = models.CharField(max_length=100, default = '')
    country = models.CharField(max_length=100, default = '')
    pincode = models.CharField(max_length=9, default = '')

class Messages(models.Model):
    pass

FoodApp/FoodServices/templates/FoodServices/addAddress.html
{% block content %}


<form method="POST" class="post-form" >  
    {% csrf_token %}  
<div class="container">  
<br>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<h3>Update Details</h3>  
</div>  
</div>  

<div class="form-group row">  
<label class="col-sm-2 col-form-label">Building:</label>  
<div class="col-sm-4">  
    <input type="text" name="building" id="id_building" required maxlength="100" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Street:</label>  
<div class="col-sm-4">  
    <input type="text" name="street" id="id_street" required maxlength="100"  />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Landmark:</label>  
<div class="col-sm-4">  
    <input type="text" name="landmark" id="id_landmark" required maxlength="100" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">City:</label>  
<div class="col-sm-4">  
    <input type="text" name="city" id="id_city" required maxlength="100"  />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">State:</label>  
<div class="col-sm-4">  
    <input type="text" name="state" id="id_state" required maxlength="100"  />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Country:</label>  
<div class="col-sm-4">  
    <input type="text" name="country" id="id_country" required maxlength="100"/>  
</div>  
</div> 
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Pin Code:</label>  
<div class="col-sm-4">  
    <input type="text" name="pincode" id="id_pincode" required maxlength="9" />  
</div>  
</div>   
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-success">Add</button>  
</div>  
</div>  
</div>  
</form>  

{% endblock %}

FoodApp/FoodServices/templates/FoodServices/dashboardFoodProvider.html
{% block content %}
<h1>
    DashBoard for Food Provider
</h1>
<div id="dashboard_fp">
    <h2> Existing Orders:-</h2>
        {% for orders in orderList %}
        <p><b> Order ID: {{ orders.order_id }} </b>
            <br> veg healthy: {{orders.veg_healthy}} , veg ill: {{orders.veg_ill}}, nonveg healthy: {{orders.nonveg_healthy}}, nonveg ill: {{orders.nonveg_ill}} 
            <br> Allergies: {{orders.allergies}}
            <br> Delivery Address: {{orders.delivery_address}}	<br>
            <hr>
        </p>
        </div>
        {% endfor %}
{% endblock %}

FoodApp/FoodServices/templates/FoodServices/dashboardFoodSeeker.html
{% block content %}
<h1>Dash Board for FoodSeeker</h1>
<div id="dashboard_fp">
    <h2> Existing Orders:-</h2>
        {% for orders in orderList %}
        <p><b> Order ID: {{ orders.order_id }} </b>
            <br> veg healthy: {{orders.veg_healthy}} , veg ill: {{orders.veg_ill}}, nonveg healthy: {{orders.nonveg_healthy}}, nonveg ill: {{orders.nonveg_ill}} 
            <br> Allergies: {{orders.allergies}}
            <br> Delivery Address: {{orders.delivery_address}}	<br>
            <hr>
        </p>
        </div>
        {% endfor %}
{% endblock %}

FoodApp/FoodServices/templates/FoodServices/editAddress.html
{% block content %}


<form method="POST" class="post-form" >  
    {% csrf_token %}  
<div class="container">  
<br>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<h3>Update Details</h3>  
</div>  
</div>  

<input type="hidden" name="add_id" value="{{ add_obj.0 }}">
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Building:</label>  
<div class="col-sm-4">  
    <input type="text" name="building" id="id_building" required maxlength="100" value="{{ add_obj.1 }}"/>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Street:</label>  
<div class="col-sm-4">  
    <input type="text" name="street" id="id_street" required maxlength="100" value="{{ add_obj.2 }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Landmark:</label>  
<div class="col-sm-4">  
    <input type="text" name="landmark" id="id_landmark" required maxlength="100" value="{{ add_obj.3 }}"/>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">City:</label>  
<div class="col-sm-4">  
    <input type="text" name="city" id="id_city" required maxlength="100" value="{{ add_obj.4 }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">State:</label>  
<div class="col-sm-4">  
    <input type="text" name="state" id="id_state" required maxlength="100" value="{{ add_obj.5 }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Country:</label>  
<div class="col-sm-4">  
    <input type="text" name="country" id="id_country" required maxlength="100" value="{{ add_obj.6 }}"/>  
</div>  
</div> 
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Pin Code:</label>  
<div class="col-sm-4">  
    <input type="text" name="pincode" id="id_pincode" required maxlength="9" value="{{ add_obj.7 }}"/>  
</div>  
</div>   
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-primary">Update</button>  
</div>  
</div>  
</div>  
</form>  

{% endblock %}

FoodApp/FoodServices/templates/FoodServices/feedbackForm.html
{%block content %}
<h2>Feedback Form for FoodSeeker</h2>
<h3>Please tell us about your previous order</h3>
<form action="" method="POST">
    {% csrf_token %}
    <label>Quality of Food</label>
    <input type="number" name="rating">
    <label>Delivered Within Time</label>
    <input type="radio" value="Yes" name="Timing"><label>Yes</label>
    <input type="radio" value="No" name="Timing"><label>No</label>
    <button class="btn btn-primary">Submit</button>
</form>

{% endblock %}

FoodApp/FoodServices/templates/FoodServices/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>

        </title>
    </head>
    <body>
        <h1>FPS</h1>

        {% block content %}
        {% endblock %}
    </body>
</html>

FoodApp/FoodServices/templates/FoodServices/loadAddress.html
{% block content %}

<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        
        <th>Address ID</th>
        <th>Building</th>  
        <th>Street</th>  
        <th>Landmark</th> 
        <th>City</th>  
        <th>State</th> 
        <th>Country</th> 
        <th>Pin Code</th>
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for address in addressList %}  
    <tr>  
        <td>{{ address.add_id }}</td>
        <td>{{ address.building }}</td> 
        <td>{{ address.street }}</td>  
        <td>{{ address.landmark }}</td>
        <td>{{ address.city }}</td>  
        <td>{{ address.state }}</td>
        <td>{{ address.country }}</td> 
        <td>{{ address.pincode }}</td>
        <td>  
            <form action="" method="POST">
                {% csrf_token %}
                <label id="edit">Edit</label>
                <input type="radio" id="edit" name="edit" value="{{ address.add_id }}" >
                <label id="delete">Delete</label>
                <input type="radio" id="delete" name="delete" value="{{ address.add_id }}" > 
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </td> 
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="addAddress" class="btn btn-primary">Add New Record</a></center>  

{% endblock %}

FoodApp/FoodServices/templates/FoodServices/signIn.html
{% block content %}
<center>
<h1>Sign In Form</h1>
<form action="" method="POST">
    {% csrf_token %}
    <label>Enter mobile Number</label>
    <input type="text" name="mobile-number">
    <br>
    <label id="number-exists"> 10 digits</label>
    <br>
    <label>Select Role</label>
    <input type="radio" name="UserType" value="FoodProvider"><label>Food Provider</label>
    <input type="radio" name="UserType" value="FoodSeeker"><label>Food Seeker</label>
    <button class="btn btn-primary">Submit</button>
</form>


{% if result == 0 %}

<script>
    
        label_id=document.getElementById("number-exists");
        console.log(label_id);
        label_id.innerHTML="<div>Number Does Not Exist<br><a>Sign Up</a></div>";
        console.log(label_id);
    
</script>
{% else %}
<script>
    label_id=document.getElementById("number-exists");
    label_id.innerHTML="";
</script>
{% endif %}
</center>
{% endblock %}

FoodApp/FoodServices/templates/FoodServices/signUp.html
{% block content %}
<center>
<h1>Sign Up Form</h1>

<form action="" method="POST">
    {% csrf_token %}
    <label id="phone-number">Enter your 10 digit mobile number</label>
    <label id="number-exists"></label>
    <input type="text" id="mobile-number" name="mobile-number">
    <br /><br />
    <label >Name</label>
    <input type="text" id="name" name="name">
    <br /><br />
    <label>Email Id</label>
    <input type="email" id="email" name="email">
    <br /><br />
    <label>Select Role</label>
    <input type="radio" value="FoodProvider" name="UserType" id="FoodProvider"><label>Food Provider</label>
    <input type="radio" value="FoodSeeker" name="UserType" id="FoodSeeker"><label>Food Seeker</label>
    <br /><br />
    <button class="btn btn-primary">Next</button>
</form>

{% if result == 1 %}

<script>
    
        label_id=document.getElementById("number-exists");
        console.log(label_id);
        label_id.innerHTML="<div>Number Exists<a>Sign In</a></div>";
        console.log(label_id);
    
</script>

{% else %}
<script>
    label_id=document.getElementById("number-exists");
    label_id.innerHTML="";
</script>
{% endif %}
</center>
{% endblock %}

FoodApp/FoodServices/templates/FoodServices/verifyUser.html
{% block content %}
<h3>OTP Sent to registered Mobile Number </h3>
<form action="" method="POST">
    {% csrf_token %}
    <label> Enter OTP</label>
    <input type="text" name="otp">
    <button class="btn btn-primary">Submit</button>
</form>

{{ mobile_number }}
{{ user_type }}

{{ user_id }}
{% endblock %}